CREATE DATABASE IF NOT EXISTS hitl_demo;
USE hitl_demo;

CREATE TABLE IF NOT EXISTS logs_hitl (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  paciente_id VARCHAR(128) NOT NULL,
  tiempo_ia DATETIME NULL,
  tiempo_humano DATETIME NULL,
  decision VARCHAR(32) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
